package by.gbyzzz.task01javalinear.controller.taskthreeimpl;

import by.gbyzzz.task01javalinear.entity.Data;
import by.gbyzzz.task01javalinear.service.ArithmeticService;
import by.gbyzzz.task01javalinear.view.IOData;

public class Guess {
    static Data in = new Data();
    static Data out = new Data();
    static Data arr = new Data();
    IOData io = new IOData();
    ArithmeticService as = new ArithmeticService();

    public void input(int i){
        io.output("Please input two numbers to compare");
        switch (i){
            case 1: io.output("Enter first number:");
                in.add(io.input());
                io.output("Enter second number:");
                in.add(io.input());
                break;
            case 2:
                break;
            case 3: //in.add(XMLIn);
                break;
            default: break;
        }

    }

    public void calculations() {
        for(int i = 0; i < 5; i++) {
            out.add(as.guess((int) in.getArr(i), 15));
        }
    }

    public void consoleOutput() {
        io.output("Numbers generated by the program are:");
        for(int i = 0; i < 5; i++){
            arr = out.getArr(i);
            io.output(arr.getArr(i));
        }
        out.clear();
        in.clear();
    }
}
